name: Server Deployment Request
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
    
    steps:
      - name: Send deployment request
        id: deploy-request
        run: |
          echo "Sending deployment request to server..."
          RESPONSE=$(curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"branch": "${{ github.ref_name }}", "commit": "${{ github.sha }}"}' \
            --fail \
            --silent \
            --show-error \
            ${{ secrets.DEPLOY_URL }})
          echo "Server response: $RESPONSE"
          
          # Extract deployment ID from response (assuming JSON response with deploymentId field)
          DEPLOYMENT_ID=$(echo $RESPONSE | jq -r '.deploymentId')
          echo "deployment_id=$DEPLOYMENT_ID" >> $GITHUB_OUTPUT
