name: Server Deployment Request
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
    
    steps:
      - name: Send deployment request
        id: deploy-request
        run: |
          echo "Sending deployment request to server..."
          RESPONSE=$(curl -X POST -H "Content-Type: application/json" --fail --silent --show-error "${{ secrets.DEPLOY_URL }}")